baseURL = "http://alburycatalina.github.io/me/"
languageCode = "en-us"
title = "Catalina Albury, BSc."
theme = "avicenna-master"
timeout=3000
publishDir = "docs"

[params]
  subtitle = "MSc Candidate"
  interests ="Omics, Bioinformatics, Scientific Outreach, Climate Justice"

[[params.affilation]]
  name = "Dalhousie University"
  position = "MSc Candidate"
  contact = "alburycatalina@dal.ca"

[[params.affilation]]
  name = "Applied Scientific Coding Society"
  position = "Co-Founder"
  contact = "asc.dal@gmail.com"



[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/alburycatalina"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/catalinaalbury"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/catalina-albury-b36a92117"

[[params.social]]
  name = "Researchgate"
  icon = "researchgate"
  url = "https://www.researchgate.net/profile/Catalina-Albury"


[[params.introduction.paragraph]]
  text="""I am a MSc researcher studying marine microbial proteomics under Dr. Erin Bertrand. Marine microbes shape global biogeomechemical cycles, and therefore our climate. My current research uses high-throughput proteomic and metabolomic approaches to provide insight on how micronutrient limitation and increasing temperatures shape diatom physiology in a changing ocean.
  
  When I'm not in the lab, you can often find me cycling, cooking, or teaching. I'm passionate about getting young people excited about ocean science and providing access to information, tools, and skills that spark scientific creativity.
  """

[[params.projects]]
	[[params.projects.project]]
		name = "Semi-Continuous Dilution Script"
		description  = "A script for maintaining phytoplankton cultures in logistic phase for steady state sampling. Input cell density and volume and it will calculate the amount of culture to remove and media to add."
		project_page = "https://github.com/alburycatalina/dilution-script"
		code_link = "https://github.com/alburycatalina/dilution-script/blob/master/predilution.R"



 [[params.projects.project]]
		name = "Intro to Coding for Jr. High"
		description  = "A 2-day introductory coding tutorial for Bahamian high school students at Forest Heights Academy"
		project_page = "https://github.com/alburycatalina/FHA_intro_to_coding"



[[params.publications]]
  year="2019"

  [[params.publications.paper]]
		name = "Honour's Thesis: The Effects of Vitamin B12 Starvation on Heat Resistance in Fragilariopsis cylindrus"
		authors = " __Catalina Albury__"
		link = "https://www.researchgate.net/publication/336720705_Effects_of_Vitamin_B12_Starvation_on_Heat_Resistance_in_Fragilariopsis_Cylindrus"
    dest = "Researchgate"


[[params.publications]]
  year="2021"

  [[params.publications.paper]]
		name = "Ecology and evolutionary biology must elevate BIPOC scholars"
		authors = " Melanie Massey, Suchinta Arif, __Catalina Albury__, Victoria Cluney"
		link = "https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13716"
    dest = "Ecology Letters"

[[params.publications]]
  year="In progress"

  [[params.publications.paper]]
    name = "Global proteomic response of the diatom Fragilariopsis cylindrus to B12 starvation and increased temperatures"
    authors = " __Catalina Albury__, Dr. Elden Rowland, Dr. Erin Bertrand"




